CREATE DATABASE IF NOT EXISTS gorder;
USE gorder;

DROP TABLE IF EXISTS `o_stock`;

CREATE TABLE `o_stock` (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    product_id VARCHAR(255) NOT NULL COMMENT '商品ID',
    quantity BIGINT UNSIGNED NOT NULL DEFAULT 0 COMMENT '库存数量',
    reserved BIGINT UNSIGNED NOT NULL DEFAULT 0 COMMENT '预占库存数量',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    KEY idx_stock_product(product_id) COMMENT '商品ID索引'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='商品库存表';

INSERT INTO `o_stock` (product_id, quantity) VALUES
('prod_TYIEBm3KnCRJn0', 100),
('prod_TWDvBbvb2pbeAH', 200);