// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.19.6
// source: stockpb/stock.proto

package stockpb

import (
	orderpb "github.com/furutachiKurea/gorder/common/genproto/orderpb"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetItemsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ItemIds       []string               `protobuf:"bytes,1,rep,name=item_ids,json=itemIds,proto3" json:"item_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetItemsRequest) Reset() {
	*x = GetItemsRequest{}
	mi := &file_stockpb_stock_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetItemsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetItemsRequest) ProtoMessage() {}

func (x *GetItemsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_stockpb_stock_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetItemsRequest.ProtoReflect.Descriptor instead.
func (*GetItemsRequest) Descriptor() ([]byte, []int) {
	return file_stockpb_stock_proto_rawDescGZIP(), []int{0}
}

func (x *GetItemsRequest) GetItemIds() []string {
	if x != nil {
		return x.ItemIds
	}
	return nil
}

type GetItemsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*orderpb.Item        `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetItemsResponse) Reset() {
	*x = GetItemsResponse{}
	mi := &file_stockpb_stock_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetItemsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetItemsResponse) ProtoMessage() {}

func (x *GetItemsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_stockpb_stock_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetItemsResponse.ProtoReflect.Descriptor instead.
func (*GetItemsResponse) Descriptor() ([]byte, []int) {
	return file_stockpb_stock_proto_rawDescGZIP(), []int{1}
}

func (x *GetItemsResponse) GetItems() []*orderpb.Item {
	if x != nil {
		return x.Items
	}
	return nil
}

type ReserveStockRequest struct {
	state         protoimpl.MessageState      `protogen:"open.v1"`
	Items         []*orderpb.ItemWithQuantity `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReserveStockRequest) Reset() {
	*x = ReserveStockRequest{}
	mi := &file_stockpb_stock_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReserveStockRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReserveStockRequest) ProtoMessage() {}

func (x *ReserveStockRequest) ProtoReflect() protoreflect.Message {
	mi := &file_stockpb_stock_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReserveStockRequest.ProtoReflect.Descriptor instead.
func (*ReserveStockRequest) Descriptor() ([]byte, []int) {
	return file_stockpb_stock_proto_rawDescGZIP(), []int{2}
}

func (x *ReserveStockRequest) GetItems() []*orderpb.ItemWithQuantity {
	if x != nil {
		return x.Items
	}
	return nil
}

type ReserveStockResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*orderpb.Item        `protobuf:"bytes,2,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReserveStockResponse) Reset() {
	*x = ReserveStockResponse{}
	mi := &file_stockpb_stock_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReserveStockResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReserveStockResponse) ProtoMessage() {}

func (x *ReserveStockResponse) ProtoReflect() protoreflect.Message {
	mi := &file_stockpb_stock_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReserveStockResponse.ProtoReflect.Descriptor instead.
func (*ReserveStockResponse) Descriptor() ([]byte, []int) {
	return file_stockpb_stock_proto_rawDescGZIP(), []int{3}
}

func (x *ReserveStockResponse) GetItems() []*orderpb.Item {
	if x != nil {
		return x.Items
	}
	return nil
}

var File_stockpb_stock_proto protoreflect.FileDescriptor

const file_stockpb_stock_proto_rawDesc = "" +
	"\n" +
	"\x13stockpb/stock.proto\x12\astockpb\x1a\x13orderpb/order.proto\",\n" +
	"\x0fGetItemsRequest\x12\x19\n" +
	"\bitem_ids\x18\x01 \x03(\tR\aitemIds\"7\n" +
	"\x10GetItemsResponse\x12#\n" +
	"\x05items\x18\x01 \x03(\v2\r.orderpb.ItemR\x05items\"F\n" +
	"\x13ReserveStockRequest\x12/\n" +
	"\x05items\x18\x01 \x03(\v2\x19.orderpb.ItemWithQuantityR\x05items\";\n" +
	"\x14ReserveStockResponse\x12#\n" +
	"\x05items\x18\x02 \x03(\v2\r.orderpb.ItemR\x05items2\x9c\x01\n" +
	"\fStockService\x12?\n" +
	"\bGetItems\x12\x18.stockpb.GetItemsRequest\x1a\x19.stockpb.GetItemsResponse\x12K\n" +
	"\fReserveStock\x12\x1c.stockpb.ReserveStockRequest\x1a\x1d.stockpb.ReserveStockResponseB:Z8github.com/furutachiKurea/gorder/common/genproto/stockpbb\x06proto3"

var (
	file_stockpb_stock_proto_rawDescOnce sync.Once
	file_stockpb_stock_proto_rawDescData []byte
)

func file_stockpb_stock_proto_rawDescGZIP() []byte {
	file_stockpb_stock_proto_rawDescOnce.Do(func() {
		file_stockpb_stock_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_stockpb_stock_proto_rawDesc), len(file_stockpb_stock_proto_rawDesc)))
	})
	return file_stockpb_stock_proto_rawDescData
}

var file_stockpb_stock_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_stockpb_stock_proto_goTypes = []any{
	(*GetItemsRequest)(nil),          // 0: stockpb.GetItemsRequest
	(*GetItemsResponse)(nil),         // 1: stockpb.GetItemsResponse
	(*ReserveStockRequest)(nil),      // 2: stockpb.ReserveStockRequest
	(*ReserveStockResponse)(nil),     // 3: stockpb.ReserveStockResponse
	(*orderpb.Item)(nil),             // 4: orderpb.Item
	(*orderpb.ItemWithQuantity)(nil), // 5: orderpb.ItemWithQuantity
}
var file_stockpb_stock_proto_depIdxs = []int32{
	4, // 0: stockpb.GetItemsResponse.items:type_name -> orderpb.Item
	5, // 1: stockpb.ReserveStockRequest.items:type_name -> orderpb.ItemWithQuantity
	4, // 2: stockpb.ReserveStockResponse.items:type_name -> orderpb.Item
	0, // 3: stockpb.StockService.GetItems:input_type -> stockpb.GetItemsRequest
	2, // 4: stockpb.StockService.ReserveStock:input_type -> stockpb.ReserveStockRequest
	1, // 5: stockpb.StockService.GetItems:output_type -> stockpb.GetItemsResponse
	3, // 6: stockpb.StockService.ReserveStock:output_type -> stockpb.ReserveStockResponse
	5, // [5:7] is the sub-list for method output_type
	3, // [3:5] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_stockpb_stock_proto_init() }
func file_stockpb_stock_proto_init() {
	if File_stockpb_stock_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_stockpb_stock_proto_rawDesc), len(file_stockpb_stock_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_stockpb_stock_proto_goTypes,
		DependencyIndexes: file_stockpb_stock_proto_depIdxs,
		MessageInfos:      file_stockpb_stock_proto_msgTypes,
	}.Build()
	File_stockpb_stock_proto = out.File
	file_stockpb_stock_proto_goTypes = nil
	file_stockpb_stock_proto_depIdxs = nil
}
